const TEST_RESPONSE_HEADER = 'x-openapi-test-response-header-';
export const TEST_RESPONSE_HEADER_TEST_ENABLED = `${TEST_RESPONSE_HEADER}test-enabled`;
export const TEST_RESPONSE_HEADER_CONTROLLER_FILE = `${TEST_RESPONSE_HEADER}controller-file`;
export const TEST_RESPONSE_HEADER_REQUEST_SCHEMA = `${TEST_RESPONSE_HEADER}request-schema`;
export const TEST_RESPONSE_HEADER_RESPONSE_HEADER_STATUS = `${TEST_RESPONSE_HEADER}response-header-status`;
export const TEST_RESPONSE_HEADER_RESPONSE_BODY_STATUS = `${TEST_RESPONSE_HEADER}response-body-status`;
export const TEST_RESPONSE_HEADER_ACTION_MUTED = `${TEST_RESPONSE_HEADER}action-muted`;
